### ISSUE TITLE
Todo 

### ISSUE THREAD

**Issue by sn99** [SubconsciousCompute/naughtyfy#3]
- [x]  Add license AGPL
- [x]  Setup CI/CD using github actions
- [x]  Convert it into a library and publish to `crates.io`
    - [x]  Add `dilawar` and `sn99` to owners list
- [x]  Improve documentation
- [x]  Move repo to [SubconsciousCompute](https://github.com/SubconsciousCompute)

**Comment by tanveerraza789** [comment]
Done!
